FROM bda/base_image:1.0

ENV PYTHONPATH /root/src/ICS5114_Practical_Assignment
ENV kafka_connection_strings "127.0.0.1:9092"
ENV stream_offset 0

CMD  /root/src/ICS5114_Practical_Assignment/recording/src/startup_producer_runner.sh
